services:
  lynx-mysql:
    image: mysql:8.0
    container_name: lynx-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - ./db_data:/var/lib/mysql
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - lynx-network

  lynx-redis:
    image: redis:7-alpine
    container_name: lynx-redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Seoul
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - lynx-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: always
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: lynx:lynx-redis:6379:0:${REDIS_PASSWORD}
    networks:
      - lynx-network
    depends_on:
      - lynx-redis

  lynx-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lynx-backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      TZ: Asia/Seoul
      DB_HOST: lynx-mysql
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: ${REDIS_HOST:-lynx-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: development
    command: npm run start:dev 
    logging:
      driver: "json-file"
      options:
        max-size: "10m"      # 로그 파일 최대 크기 (10MB)
        max-file: "3"         # 보관할 로그 파일 개수 (3개)
    depends_on:
      - lynx-mysql
      - lynx-redis
    networks:
      - lynx-network

volumes:
  redis_data:

networks:
  lynx-network:
    driver: bridge